info:
  amd: ${LANGUAGE:USA}

server:
  port: ${SERVICE_PORT:8081}
  undertow:
    max-http-post-size: 104857600

spring:
  http:
    multipart:
      maxFileSize: 1MB  #单个文件最大为20M
      maxRequestSize: 1MB #单次请求文件总数大小为20M